// Mocks generated by Mockito 5.4.0 from annotations
// in security_cam/test/src/app/infra/repositories/security_cam_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:security_cam/src/app/infra/datasources/security_cam_datasource.dart'
    as _i4;
import 'package:security_cam/src/app/infra/models/authentication/authentication_model.dart'
    as _i3;
import 'package:security_cam/src/app/infra/models/recording/recording_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRecordingModel_0 extends _i1.SmartFake
    implements _i2.RecordingModel {
  _FakeRecordingModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthenticationModel_1 extends _i1.SmartFake
    implements _i3.AuthenticationModel {
  _FakeAuthenticationModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SecurityCamDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecurityCamDatasource extends _i1.Mock
    implements _i4.SecurityCamDatasource {
  MockSecurityCamDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.RecordingModel> getSecurityRecordings({int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSecurityRecordings,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Future<_i2.RecordingModel>.value(_FakeRecordingModel_0(
          this,
          Invocation.method(
            #getSecurityRecordings,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i5.Future<_i2.RecordingModel>);
  @override
  _i5.Future<_i3.AuthenticationModel> loginValidation({
    required String? user,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginValidation,
          [],
          {
            #user: user,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i3.AuthenticationModel>.value(
            _FakeAuthenticationModel_1(
          this,
          Invocation.method(
            #loginValidation,
            [],
            {
              #user: user,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i3.AuthenticationModel>);
}
